---
atop_log_interval: 600
atop_log_generations: 28

ntpd_servers:
  - ntp1.mail.ru
  - ntp2.mail.ru

node_exporter_version: 1.3.1

nginx_enable_default: no

# Nginx limits
nginx_conn_limits:
  - name: conn_limit_per_ip
    field: "$binary_remote_addr"
    max_conn: 40 # default value
nginx_rate_limits:
  - name: req_limit_per_ip
    field: "$binary_remote_addr"
    rate:  150r/s
    burst: 50    # default value

# Get only names: nginx_sites | map(attribute='name') | flatten
nginx_sites:
  - name: mysite # default site (0.0.0.0)
    server_name: enterprise.vm
    addr: 0.0.0.0
    static_root: "/var/www/mysite/"
    static_path: /
    static_hard: yes
    basic_auth: yes
    hosts: all
    ssl: no
    redirect: no
    whitelist:
      - external

  - name: node_exporter
    server_name: node.enterprise.vm
    addr: "{{ ansible_default_ipv4['address'] }}"
    local: yes
    port: 9100
    hosts: all
    ssl: no
    redirect: no
